name			= "KAM Compat ZEN [Beta] v0.0.0";	// Name of your mod
author			= "Andx";					// Affects Arma 3 Launcher, when the mod are loaded as local
logo			= "img\icon.paa";			// Logo displayed in the main menu
logoOver		= "img\icon.paa";			// When the mouse is over, in the main menu
tooltip			= "KAM Compat ZEN";
tooltipOwned	= "KAM Compat ZEN";			// Tool tip displayed when the mouse is left over, in the main menu
picture			= "img\icon.paa";			// Picture displayed from the expansions menu. Optimal size is 2048x1024
actionName		= "GitHub";
action			= "https://github.com/Andx667/kam_compat_zen";	// Website URL, that can be accessed from the expansions menu
overview		= "Compatibility patch between KAT - Advanced Medical (KAM) and Zeus Enhanced (ZEN).";	// Supports structured text
hideName		= 0;						// Hide the extension name
hidePicture		= 0;						// Hide the extension menu
dlcColor[]		= { 0.23, 0.39, 0.30, 1 };	// Color used for DLC stripes and backgrounds (RGBA)
logoSmall		= "img\icon.paa";			// Display in creative lists, next to the entities added by the mod
