name = "KAM Compat ZEN"
author = "Andx"
prefix = "kcz"
mainprefix = "z"

[version]
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "LICENSE",
    "README.md",
    "img/icon.paa",
    "img/icon.png"
]
