name = "KAM Compat ZEN"
author = "Andx"
prefix = "kcz"
mainprefix = "z"

[version]
major = 0
minor = 1
patch = 0
build = 0
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "LICENSE",
    "README.md",
]
